// seal.go — the contract's sealed identity (orun-tasks O1, TK-J/TK-7).
//
// ContractID is the Go twin of the cloud's contractHash (orun-cloud
// packages/contracts/src/tasks.ts): "sha256:<hex>" over the contract's
// canonical JSON — lexicographically sorted keys, empty fields omitted (the
// struct's omitempty tags), no insignificant whitespace. The cloud VERIFIES
// this hash on attach and stores it as the identity every gate decision
// cites, so the two implementations must agree byte for byte; the embedded
// conformance fixture (generated BY the TypeScript twin) pins that they do.
//
// Why a second canonicalizer beside CanonicalJSON: the wire form is defined
// by the TypeScript side, and JSON.stringify does not HTML-escape — while
// Go's encoding/json escapes '<', '>' and '&' (and U+2028/U+2029) inside
// strings. Brief identity has always used the escaping form and existing
// sealed ids must not move, so the contract seal gets its own leaf encoder
// instead of changing appendCanonical under the briefs.

package contract

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"unicode/utf8"
)

// ContractID returns the contract's sealed identity — "sha256:<hex>" over its
// canonical JSON in the WIRE form the cloud verifies — plus those canonical
// bytes (what `orun task` uploads, and what the task node's tree bundles).
func ContractID(c *Contract) (string, []byte, error) {
	raw, err := json.Marshal(c)
	if err != nil {
		return "", nil, fmt.Errorf("contract: encode for seal: %w", err)
	}
	var tree interface{}
	if err := json.Unmarshal(raw, &tree); err != nil {
		return "", nil, fmt.Errorf("contract: decode for seal: %w", err)
	}
	canonical, err := appendCanonicalWire(make([]byte, 0, len(raw)), tree)
	if err != nil {
		return "", nil, err
	}
	sum := sha256.Sum256(canonical)
	return "sha256:" + hex.EncodeToString(sum[:]), canonical, nil
}

// appendCanonicalWire mirrors appendCanonical with one difference: string
// leaves and keys use the wire (JSON.stringify-compatible) escaping.
func appendCanonicalWire(out []byte, v interface{}) ([]byte, error) {
	switch t := v.(type) {
	case map[string]interface{}:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		out = append(out, '{')
		for i, k := range keys {
			if i > 0 {
				out = append(out, ',')
			}
			var err error
			out, err = appendWireString(out, k)
			if err != nil {
				return nil, err
			}
			out = append(out, ':')
			out, err = appendCanonicalWire(out, t[k])
			if err != nil {
				return nil, err
			}
		}
		return append(out, '}'), nil
	case []interface{}:
		out = append(out, '[')
		for i, e := range t {
			if i > 0 {
				out = append(out, ',')
			}
			var err error
			out, err = appendCanonicalWire(out, e)
			if err != nil {
				return nil, err
			}
		}
		return append(out, ']'), nil
	case string:
		return appendWireString(out, t)
	default:
		// Numbers, booleans, null — no escaping differences exist for these.
		b, err := json.Marshal(t)
		if err != nil {
			return nil, err
		}
		return append(out, b...), nil
	}
}

// appendWireString encodes one JSON string exactly the way JSON.stringify
// does: the two mandatory escapes (quote, backslash), the short forms for
// \b \f \n \r \t, \u00xx for the remaining control characters, and every
// other code point \u2014 including '<', '>', '&' and U+2028/U+2029 \u2014 emitted as
// raw UTF-8. Implemented by hand rather than post-processing encoding/json's
// output, because un-escaping with a byte replace corrupts text that
// contains a literal backslash-u sequence.
func appendWireString(out []byte, s string) ([]byte, error) {
	out = append(out, '"')
	for _, r := range s {
		switch r {
		case '"':
			out = append(out, '\\', '"')
		case '\\':
			out = append(out, '\\', '\\')
		case '\b':
			out = append(out, '\\', 'b')
		case '\f':
			out = append(out, '\\', 'f')
		case '\n':
			out = append(out, '\\', 'n')
		case '\r':
			out = append(out, '\\', 'r')
		case '\t':
			out = append(out, '\\', 't')
		default:
			if r < 0x20 {
				out = append(out, fmt.Sprintf(`\u%04x`, r)...)
			} else {
				out = utf8.AppendRune(out, r)
			}
		}
	}
	return append(out, '"'), nil
}
