package contract

import (
	_ "embed"
	"encoding/json"
	"testing"
)

// The cross-implementation seal pin (orun-tasks O1, TK-7): the fixture was
// GENERATED by the TypeScript twin (orun-cloud packages/contracts/src/tasks.ts
// contractHash / canonicalContractJson — the code the cloud runs when it
// verifies an attach), so this test failing means the two implementations
// have diverged on bytes, and the cloud would refuse seals this side writes.
//
//go:embed fixtures/contract-hash-conformance.json
var contractHashConformance []byte

type hashConformance struct {
	Version int `json:"version"`
	Cases   []struct {
		Name      string   `json:"name"`
		Contract  Contract `json:"contract"`
		Canonical string   `json:"canonical"`
		Hash      string   `json:"hash"`
	} `json:"cases"`
}

func TestContractIDConformance(t *testing.T) {
	var corpus hashConformance
	if err := json.Unmarshal(contractHashConformance, &corpus); err != nil {
		t.Fatalf("decode fixture: %v", err)
	}
	if corpus.Version != 1 || len(corpus.Cases) == 0 {
		t.Fatalf("fixture version %d with %d cases", corpus.Version, len(corpus.Cases))
	}
	for _, c := range corpus.Cases {
		id, canonical, err := ContractID(&c.Contract)
		if err != nil {
			t.Fatalf("%s: %v", c.Name, err)
		}
		if string(canonical) != c.Canonical {
			t.Errorf("%s: canonical bytes diverge from the TypeScript twin\n got:  %s\n want: %s", c.Name, canonical, c.Canonical)
		}
		if id != c.Hash {
			t.Errorf("%s: hash %s, twin computed %s", c.Name, id, c.Hash)
		}
	}
}

func TestContractIDRevisionAndDedup(t *testing.T) {
	a := &Contract{Goal: "ship it", Affects: []string{"web"}, DoneWhen: []string{"done"}, Gates: []string{"tests"}}
	b := &Contract{Goal: "ship it", Affects: []string{"web"}, DoneWhen: []string{"done"}, Gates: []string{"tests"}}
	idA, _, err := ContractID(a)
	if err != nil {
		t.Fatal(err)
	}
	idB, _, err := ContractID(b)
	if err != nil {
		t.Fatal(err)
	}
	// Identical contracts seal to one identity — the dedup property.
	if idA != idB {
		t.Fatalf("identical contracts sealed differently: %s vs %s", idA, idB)
	}
	// A revision — any content change — mints a new identity.
	b.Envs = []string{"dev"}
	idB2, _, err := ContractID(b)
	if err != nil {
		t.Fatal(err)
	}
	if idB2 == idA {
		t.Fatal("a revised contract kept its predecessor's identity")
	}
}

func TestContractIDOmitsEmptyAndFalse(t *testing.T) {
	// Empty slices, empty strings and gatesDefined:false must all vanish from
	// the canonical form — the TS side drops them explicitly, this side via
	// omitempty; if either stops, the hashes walk apart.
	_, canonical, err := ContractID(&Contract{Gates: []string{}, GatesDefined: false, Secrets: []string{}})
	if err != nil {
		t.Fatal(err)
	}
	if string(canonical) != "{}" {
		t.Fatalf("empty contract canonicalized to %s", canonical)
	}
}

func TestCompleteUnchangedByEnforcementFields(t *testing.T) {
	// Secrets/Envs narrow enforcement; they are deliberately NOT part of
	// "actionable" — a contract with only narrowing fields is still a draft.
	c := &Contract{Secrets: []string{"K_*"}, Envs: []string{"dev"}}
	if c.Complete() {
		t.Fatal("narrowing fields alone must not make a contract complete")
	}
}
